In [2]:
from datetime import datetime
import requests

start_year = datetime.now().year - 5
end_year = datetime.now().year
current_month = datetime.now().month

url = "https://earthquake.usgs.gov/fdsnws/event/1/query"

earthquake_data = []

for year in range(start_year, end_year + 1):

    if year == end_year:
        last_month = current_month
    else:
        last_month = 12

    for month in range(1, last_month + 1):

        start_date = f"{year}-{month:02d}-01"

        if month == 12:
            end_date = f"{year + 1}-01-01"
        else:
            end_date = f"{year}-{month + 1:02d}-01"

        params = {
            "format": "geojson",
            "starttime": start_date,
            "endtime": end_date,
            "minmagnitude": 3
        }

        response = requests.get(url, params=params)

        if response.status_code == 200:
            data = response.json()
            features = data["features"]
            earthquake_data.extend(features)

        print(start_date, "completed")

2021-01-01 completed
2021-02-01 completed
2021-03-01 completed
2021-04-01 completed
2021-05-01 completed
2021-06-01 completed
2021-07-01 completed
2021-08-01 completed
2021-09-01 completed
2021-10-01 completed
2021-11-01 completed
2021-12-01 completed
2022-01-01 completed
2022-02-01 completed
2022-03-01 completed
2022-04-01 completed
2022-05-01 completed
2022-06-01 completed
2022-07-01 completed
2022-08-01 completed
2022-09-01 completed
2022-10-01 completed
2022-11-01 completed
2022-12-01 completed
2023-01-01 completed
2023-02-01 completed
2023-03-01 completed
2023-04-01 completed
2023-05-01 completed
2023-06-01 completed
2023-07-01 completed
2023-08-01 completed
2023-09-01 completed
2023-10-01 completed
2023-11-01 completed
2023-12-01 completed
2024-01-01 completed
2024-02-01 completed
2024-03-01 completed
2024-04-01 completed
2024-05-01 completed
2024-06-01 completed
2024-07-01 completed
2024-08-01 completed
2024-09-01 completed
2024-10-01 completed
2024-11-01 completed
2024-12-01 completed
2025-01-01 completed
2025-02-01 completed
2025-03-01 completed
2025-04-01 completed
2025-05-01 completed
2025-06-01 completed
2025-07-01 completed
2025-08-01 completed
2025-09-01 completed
2025-10-01 completed
2025-11-01 completed
2025-12-01 completed
2026-01-01 completed
2026-02-01 completed
2026-03-01 completed
2026-04-01 completed
2026-05-01 completed
2026-06-01 completed
2026-07-01 completed
2026-08-01 completed
2026-09-01 completed

In [3]:
print("Total records:", len(earthquake_data))

Total records: 119103

In [6]:
import pandas as pd
all_records = []

for f in earthquake_data:
    p = f["properties"]
    g = f["geometry"]["coordinates"]

    all_records.append({
        "id": f.get("id"),
        "time": pd.to_datetime(p.get("time"), unit="ms"),
        "updated": pd.to_datetime(p.get("updated"), unit="ms"),
        "latitude": g[1] if g else None,
        "longitude": g[0] if g else None,
        "depth_km": g[2] if g else None,
        "mag": p.get("mag"),
        "magType": p.get("magType"),
        "place": p.get("place"),
        "status": p.get("status"),
        "tsunami": p.get("tsunami"),
        "alert": p.get("alert"),
        "felt": p.get("felt"),
        "cdi": p.get("cdi"),
        "mmi": p.get("mmi"),
        "sig": p.get("sig"),
        "net": p.get("net"),
        "code": p.get("code"),
        "ids": p.get("ids"),
        "sources": p.get("sources"),
        "types": p.get("types"),
        "nst": p.get("nst"),
        "dmin": p.get("dmin"),
        "rms": p.get("rms"),
        "gap": p.get("gap"),
        "type": p.get("type")
    })

In [7]:
print(len(all_records))

119103

In [9]:
df = pd.DataFrame(all_records)
print(df.shape)

(119103, 26)

In [10]:
print(df.columns)

Index(['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag',
       'magType', 'place', 'status', 'tsunami', 'alert', 'felt', 'cdi', 'mmi',
       'sig', 'net', 'code', 'ids', 'sources', 'types', 'nst', 'dmin', 'rms',
       'gap', 'type'],
      dtype='str')

In [11]:
df.isnull().sum()

id                0
time              0
updated           0
latitude          0
longitude         0
depth_km          0
mag               0
magType           0
place             0
status            0
tsunami           0
alert        114232
felt         100977
cdi          100977
mmi          108578
sig               0
net               0
code              0
ids               0
sources           0
types             0
nst           27762
dmin           3978
rms              19
gap            3024
type              0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.dtypes

id                      str
time         datetime64[ms]
updated      datetime64[ms]
latitude            float64
longitude           float64
depth_km            float64
mag                 float64
magType                 str
place                   str
status                  str
tsunami               int64
alert                   str
felt                float64
cdi                 float64
mmi                 float64
sig                   int64
net                     str
code                    str
ids                     str
sources                 str
types                   str
nst                 float64
dmin                float64
rms                 float64
gap                 float64
type                    str
dtype: object

In [16]:
print("Maximum Magnitude:" ,df["mag"].max())
print("Minimum Magnitude:" ,df["mag"].min())

Maxium Magnitude: 8.8
Minimum Magnitude: 3.0

In [18]:
print("Minimum Latitude :",df["latitude"].min())
print("Maximum Latitude :",df["latitude"].max())

Minimum Latitude : -84.4932
Maximum Latitude : 87.3752

In [19]:
print("Minimum Longitude :", df["longitude"].min())
print("Maximum Longitude :", df["longitude"].max())

Minimum Longitude : -179.9997
Maximum Longitude : 179.9994

In [20]:
print("Minimum Depth :", df["depth_km"].min())
print("Maximum Depth :", df["depth_km"].max())

Minimum Depth : -3.74
Maximum Depth : 683.578

In [21]:
negative_depth = df[df["depth_km"] < 0]

print(negative_depth[["id", "place", "depth_km", "mag"]])

                id                                 place  depth_km   mag
740     hv72324192             8 km N of Naalehu, Hawaii     -0.27  3.21
1318    hv72314312  26 km E of Honaunau-Napoopoo, Hawaii     -1.46  3.15
4230    hv72388857          20 km WNW of Volcano, Hawaii     -1.62  3.10
4232    hv72388852          20 km WNW of Volcano, Hawaii     -2.41  3.51
4913    ci39575335       65km NNW of Stovepipe Wells, CA     -1.36  3.21
...            ...                                   ...       ...   ...
116523  uu80145026   2 km WNW of Little America, Wyoming     -2.74  3.19
116869  uu80143896   2 km WNW of Little America, Wyoming     -1.93  3.16
117444  uu80149666   2 km NNW of Little America, Wyoming     -2.84  3.12
118140  uu80148271    2 km NW of Little America, Wyoming     -1.73  3.29
119000  uu80153696   2 km NNW of Little America, Wyoming     -2.22  3.00

[117 rows x 4 columns]

In [22]:
print("Number of negative-depth records:", len(negative_depth))

Number of negative-depth records: 117

In [23]:
print((df["depth_km"] <= 0).sum())

1031

In [24]:
df["depth_km"].describe()

count    119103.000000
mean         71.428255
std         122.799979
min          -3.740000
25%          10.000000
50%          21.154000
75%          70.587500
max         683.578000
Name: depth_km, dtype: float64

In [25]:
df[["mag", "depth_km"]].describe()

                 mag       depth_km
count  119103.000000  119103.000000
mean        4.256058      71.428255
std         0.610821     122.799979
min         3.000000      -3.740000
25%         4.000000      10.000000
50%         4.300000      21.154000
75%         4.600000      70.587500
max         8.800000     683.578000

In [36]:
df["year"] = df["time"].dt.year
df["month"]=df["time"].dt.month
df["day"]=df["time"].dt.day
df["day of week"]=df["time"].dt.day_name()

In [37]:
df[["time","year","month","day","day of week"]].head()

                     time  year  month  day day of week
0 2021-01-31 23:20:49.923  2021      1   31      Sunday
1 2021-01-31 23:08:17.161  2021      1   31      Sunday
2 2021-01-31 22:54:19.760  2021      1   31      Sunday
3 2021-01-31 22:06:00.832  2021      1   31      Sunday
4 2021-01-31 21:51:14.016  2021      1   31      Sunday

In [38]:
df = pd.DataFrame(all_records)

In [39]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print(df.head())

Rows: 119103
Columns: 26
           id                    time                 updated  latitude  \
0  us6000ddi8 2021-01-31 23:20:49.923 2021-04-16 19:02:44.040  -31.7493
1  us6000dev6 2021-01-31 23:08:17.161 2021-04-16 19:03:47.040  -15.4902
2  us6000dev5 2021-01-31 22:54:19.760 2021-04-16 19:03:47.040   19.7529
3  us6000ddhs 2021-01-31 22:06:00.832 2021-04-16 19:02:43.040   28.1524
4  us6000dev4 2021-01-31 21:51:14.016 2021-04-16 19:03:46.040   71.3212

   longitude  depth_km  mag magType  \
0   -68.9337     17.27  4.7     mwr
1  -177.2052    426.71  4.1      mb
2   121.3159     46.73  4.7      mb
3    57.2570     10.00  4.9      mb
4    -3.7578     10.00  4.0      mb

                                               place    status  ...  net  \
0        29 km SW of Villa Basilio Nievas, Argentina  reviewed  ...   us
1                                        Fiji region  reviewed  ...   us
2                    103 km SW of Basco, Philippines  reviewed  ...   us
3                            114 km N of M?n?b, Iran  reviewed  ...   us
4  184 km ENE of Olonkinbyen, Svalbard and Jan Mayen  reviewed  ...   us

       code           ids  sources                                   types  \
0  6000ddi8  ,us6000ddi8,     ,us,  ,dyfi,moment-tensor,origin,phase-data,
1  6000dev6  ,us6000dev6,     ,us,                     ,origin,phase-data,
2  6000dev5  ,us6000dev5,     ,us,                     ,origin,phase-data,
3  6000ddhs  ,us6000ddhs,     ,us,                     ,origin,phase-data,
4  6000dev4  ,us6000dev4,     ,us,                     ,origin,phase-data,

   nst   dmin   rms    gap        type
0  NaN  0.294  0.82   42.0  earthquake
1  NaN  1.471  0.29   64.0  earthquake
2  NaN  3.057  0.69  106.0  earthquake
3  NaN  3.330  0.61   71.0  earthquake
4  NaN  6.023  0.50   65.0  earthquake

[5 rows x 26 columns]

In [40]:
df.columns

Index(['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag',
       'magType', 'place', 'status', 'tsunami', 'alert', 'felt', 'cdi', 'mmi',
       'sig', 'net', 'code', 'ids', 'sources', 'types', 'nst', 'dmin', 'rms',
       'gap', 'type'],
      dtype='str')

In [41]:
print(df)

                   id                    time                 updated  \
0          us6000ddi8 2021-01-31 23:20:49.923 2021-04-16 19:02:44.040
1          us6000dev6 2021-01-31 23:08:17.161 2021-04-16 19:03:47.040
2          us6000dev5 2021-01-31 22:54:19.760 2021-04-16 19:03:47.040
3          us6000ddhs 2021-01-31 22:06:00.832 2021-04-16 19:02:43.040
4          us6000dev4 2021-01-31 21:51:14.016 2021-04-16 19:03:46.040
...               ...                     ...                     ...
119098     us7000tdbz 2026-09-01 04:50:45.457 2026-09-01 20:23:31.864
119099  aka2026rhblzv 2026-09-01 03:04:24.961 2026-09-01 16:13:24.871
119100     pr71530493 2026-09-01 03:03:51.600 2026-09-01 09:34:39.270
119101     us7000td94 2026-09-01 02:22:48.557 2026-09-01 16:08:36.998
119102     us7000td8u 2026-09-01 01:29:10.774 2026-09-01 01:44:48.040

        latitude  longitude  depth_km   mag magType  \
0       -31.7493   -68.9337    17.270  4.70     mwr
1       -15.4902  -177.2052   426.710  4.10      mb
2        19.7529   121.3159    46.730  4.70      mb
3        28.1524    57.2570    10.000  4.90      mb
4        71.3212    -3.7578    10.000  4.00      mb
...          ...        ...       ...   ...     ...
119098    8.6353   -82.4204    10.000  3.60      ml
119099   51.4140  -177.0380    40.200  3.00      ml
119100   18.4445   -68.2475    93.890  3.42      md
119101   55.9965  -161.1496   192.579  3.30      ml
119102  -20.4066  -177.9940   533.035  4.80      mb

                                                    place    status  ...  net  \
0             29 km SW of Villa Basilio Nievas, Argentina  reviewed  ...   us
1                                             Fiji region  reviewed  ...   us
2                         103 km SW of Basco, Philippines  reviewed  ...   us
3                                 114 km N of M?n?b, Iran  reviewed  ...   us
4       184 km ENE of Olonkinbyen, Svalbard and Jan Mayen  reviewed  ...   us
...                                                   ...       ...  ...  ...
119098                        4 km WSW of Caldera, Panama  reviewed  ...   us
119099                          58 km SSW of Adak, Alaska  reviewed  ...   ak
119100         22 km SE of Punta Cana, Dominican Republic  reviewed  ...   pr
119101                    3 km E of Nelson Lagoon, Alaska  reviewed  ...   us
119102                         292 km WNW of Houma, Tonga  reviewed  ...   us

               code                         ids  sources  \
0          6000ddi8                ,us6000ddi8,     ,us,
1          6000dev6                ,us6000dev6,     ,us,
2          6000dev5                ,us6000dev5,     ,us,
3          6000ddhs                ,us6000ddhs,     ,us,
4          6000dev4                ,us6000dev4,     ,us,
...             ...                         ...      ...
119098     7000tdbz                ,us7000tdbz,     ,us,
119099  a2026rhblzv             ,aka2026rhblzv,     ,ak,
119100     71530493                ,pr71530493,     ,pr,
119101     7000td94  ,aka2026rhabwz,us7000td94,  ,ak,us,
119102     7000td8u                ,us7000td8u,     ,us,

                                         types   nst    dmin   rms    gap  \
0       ,dyfi,moment-tensor,origin,phase-data,   NaN  0.2940  0.82   42.0
1                          ,origin,phase-data,   NaN  1.4710  0.29   64.0
2                          ,origin,phase-data,   NaN  3.0570  0.69  106.0
3                          ,origin,phase-data,   NaN  3.3300  0.61   71.0
4                          ,origin,phase-data,   NaN  6.0230  0.50   65.0
...                                        ...   ...     ...   ...    ...
119098                ,dyfi,origin,phase-data,   6.0  1.0260  0.38  225.0
119099                     ,origin,phase-data,  26.0  0.4000  0.50  213.0
119100                     ,origin,phase-data,  13.0  0.1445  0.41  176.0
119101                     ,origin,phase-data,  16.0  0.6760  0.61  132.0
119102                     ,origin,phase-data,  69.0  4.5810  1.00   63.0

              type
0       earthquake
1       earthquake
2       earthquake
3       earthquake
4       earthquake
...            ...
119098  earthquake
119099  earthquake
119100  earthquake
119101  earthquake
119102  earthquake

[119103 rows x 26 columns]

In [47]:
df.to_csv("Earthquake_data.csv", index=False)